### ISSUE TITLE
Question about inverse operator

### ISSUE THREAD

**Issue by ceilingFan456** [jmaces/aapm-ct-challenge#1]
Hello, I have a question about the implementation of filtered back projection. After solving the integral, x is divided by the spacing between detectors. What is the reason for doing this? Thank you.  

https://github.com/jmaces/aapm-ct-challenge/blob/81cdf946438ea2227eb4007f9e3ac4e546d4b0c4/aapm-ct/operators.py#L509C2-L509C39

**Comment by jmaces** [comment]
The code part you referenced is not the inverse operator but the [adjoint](https://en.wikipedia.org/wiki/Hermitian_adjoint). It is a numerical approximation of an integral that is summing along the discrete detector elements. Dividing by the spacing is a normalization factor for the integral to make this the proper adjoint.

**Comment by ceilingFan456** [comment]
Thank you for the clarification. And Thank you for the awesome work too :D
